- apt: name="{{ item }}"
  with_items:
  - libev4
  - libxcb-xinerama0
- copy: src=i3lock dest=/usr/bin/i3lock mode=u+x
- copy: src=i3lock.service dest=/etc/systemd/system/i3lock.service
- copy:
    content: |
      #!/bin/sh
      xhost +
    dest: /etc/display.sh
- file:
    path: /etc/display.sh
    mode: u+rwx
