# https://www.howtogeek.com/117994/how-to-disable-ubuntus-guest-session-account/
- name: Configure LightDM
  copy:
    src: lightdm.conf
    dest: /etc/lightdm/lightdm.conf

- file: path=/root/drivers/ state=directory

# Disable wifi: blacklist kernel module, move module files
- name: Disable WiFi
  kernel_blacklist:
    name: "{{ item }}"
  with_items:
  - brcmfmac
  - brcmutil
- name: Remove wifi kernel modules
  shell: creates="/root/drivers/wireless" mv /lib/modules/$(uname -r)/kernel/drivers/net/wireless /root/drivers/

# Disable bluetooth: blacklist kernel module, move module files
- name: Disable Bluetooth
  kernel_blacklist:
    name: "{{ item }}"
  with_items:
  - btbcm
  - hci_uart
- name: Remove bluetooth modules
  shell: creates="/root/drivers/bluetooth" mv /lib/modules/$(uname -r)/kernel/drivers/bluetooth /root/drivers/

- name: Remove USB storage modules
  shell: creates="/root/drivers/usb-storage.ko" mv /lib/modules/$(uname -r)/kernel/drivers/usb/storage/usb-storage.ko /root/drivers/
- copy:
    content: |
      rmmod usb
      rmmod usb_storage
      exit 0
    dest: /etc/rc.local

- apt: name=auditd
- copy: src=audit.rules dest=/etc/audit/audit.rules
