- apt: name="{{ item }}"
  with_items:
  - rsync
  - btrfs-tools
- shell: creates=/backup.fs dd if=/dev/zero of=/backup.fs bs=1M count=100K
  register: result
- shell: losetup -d /dev/loop7; losetup /dev/loop7 /backup.fs
  when: result.changed
- shell: mkfs.btrfs -f /dev/loop7
  when: result.changed
- file: path=/backup/ state=directory
- mount:
    path: /backup
    src: /dev/loop7
    fstype: btrfs
    opts: compress=lzo
    state: mounted
- synchronize:
    src: backupista/
    dest: /backupista/
- cron:
    name: "backup_snapshot"
    minute: "*/5"
    job: "/backupista/snapshot.sh >/var/log/backupista.log 2>&1"
    # special_time: reboot
    state: absent
- cron:
    name: "backup_sync"
    minute: "*/10"
    job: "/backupista/backup-all.sh >/var/log/backupista.log 2>&1"
    state: absent
