- hosts: image-mother
  tasks:
  - template:
      src: dhcp_interfaces
      dest: /etc/network/interfaces
  - copy:
      content: |
        Acquire::HTTP::Proxy "http://192.168.90.191:3142";
        Acquire::HTTPS::Proxy "false";
      dest: /etc/apt/apt.conf.d/01cacher
- hosts: image-mother
  roles:
  - role: contestant
  - role: zabbix/agent
  - role: ntp
    ntp_server: 192.168.33.1

- hosts: image-mother
  name: Customize user's profile
  tasks:
  - pause: minutes=10 prompt="Login!"
  - file: path=/etc/apt/apt.conf.d/01cacher state=absent
  - shell: creates=/home/ioi/.mozilla/firefox/ioi.default sudo -H -u ioi DISPLAY=:0 firefox -CreateProfile "ioi.default /home/ioi/.mozilla/firefox/ioi.default"
  - lineinfile:
      path: /home/ioi/.mozilla/firefox/ioi.default/prefs.js
      regexp: 'user_pref\("browser\.startup\.homepage"'
      line: 'user_pref("browser.startup.homepage", "{{ homepage }}");'
  - copy: src=power.sh dest=/tmp/power.sh
  - shell: creates=/home/ioi/.power sudo -H -u ioi DISPLAY=:0 sh /tmp/power.sh

- hosts: image-mother
  tasks:
  - copy: content="contestant-1.0.0" dest=/etc/ioi_version
