- apt: name=apt-transport-https

# from: get.docker.io
- copy: src=key.gpg dest=/tmp/docker.gpg
- apt_key: file=/tmp/docker.gpg
- copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=amd64] https://apt.dockerproject.org/repo ubuntu-xenial main

- apt: update_cache=yes
- apt: name=docker-engine
