- hosts: contestant
  gather_facts: no
  tasks:
  - hostname: name="pc{{ pc }}"
  - template: src=hosts dest=/etc/hosts

- hosts: contestant
  tasks:
  - template:
      src: static_interfaces
      dest: /etc/network/interfaces

- name: Enable/Start monitoring agent
  gather_facts: no
  hosts: contestant
  tasks:
  - systemd:
      state: restarted
      enabled: true
      name: zabbix-agent
